#!/usr/bin/env python3
import os
import ase
import argparse

from module.outcar import Outcar

def main():
    parser = argparse.ArgumentParser(description="Obtain first principle data from OUTCAR files generated by on-the-fly training and write it to a database file.")
    # Positional arguments
    parser.add_argument("outcar_files", type=str, nargs="+",
                        help="Path to OUTCAR files to be loaded")

    # Optional arguments
    parser.add_argument("-fn", "--file_name", type=str, default=None,
                        help="Name of new ML_ABN file.")

    parser.add_argument("-m", "--method", type=str, default="dft",
                        help="Type of data to extract (e.g., 'dft', 'mlff', 'both').")

    # Parse the arguments
    args = parser.parse_args()

    outcar_files = []
    for outcar_file in args.outcar_files:
        outcar_files.append(os.path.abspath(outcar_file))

    oc = Outcar()

    all_outcar_data = []
    for outcar_path in outcar_files:
        outcar_data = oc.load(outcar_path)
        outcar_data = oc.filter_data(outcar_data, args.method)

        all_outcar_data.extend(outcar_data)

    db_name = args.file_name
    if db_name is None:
        db_name = os.path.basename(outcar_files[0])

    if not db_name.endswith(".db"):
        db_name += ".db"

    cwd = os.getcwd()
    db_path = os.path.join(cwd, db_name)

    if os.path.exists(db_path):
        raise FileExistsError(f"{db_path} already exists.")

    oc.write2db(all_outcar_data, db_path)

if __name__ == "__main__":
    main()
